### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#12]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=25487218)](https://www.bountysource.com/issues/25487218-coding-style?utm_source=25487218&utm_medium=shield&utm_campaign=ISSUE_BADGE)
Coding style needs to be fixed and tested on CI :smile:

**Comment by sumedh123** [comment]
@PeterDaveHello I didn't get by the term "Coding style needs to be fixed". can you elaborate what kind of changes are needed in coding style?

**Comment by PeterDaveHello** [comment]
Hi @sumedh123 , thanks for asking, currently, there is no coding style lint / test, we'd like to enable it on Travis CI, so that every pull request and push can be tested, to maintain the code readability and the maintainability :)

**Comment by jman294** [comment]
JSCS seems to be deprecated and merged with ESLint. Are you interested in switching, or is it not worth it?

**Comment by PeterDaveHello** [comment]
I think we can switch later.

This issue was solved in 
-ab1dc9d7726ad6e80d9e8aad856ba1585984a1b3 - 3aeaee486511936391269f6480f811f26661a59b - 767160e1aaa8b01bd384bd20251b55ead2fcd967 - 29240f5408e307e43496099a6cd375fbf5e73700
