### ISSUE TITLE
Support multiple filemap

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#13]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=25518638)](https://www.bountysource.com/issues/25518638-support-multiple-filemap?utm_source=25518638&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Currently, the `autoupdate` field in `package.json` only support single base path with single file list like this:

``` js
  "autoupdate": {
     "source": "git",
     "target": "git://github.com/cdnjs/cdnjs.git",
     "basePath": "",
     "files": [
       "*.json"
     ]
  }
```

We did support multi-filemap in npm auto-update like this (take `waterfall.js` as example):

``` js
  "npmName": "waterfall.js",
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "waterfall*"
      ]
    },
    {
      "basePath": "src",
      "files": [
        "waterfall*"
      ]
    }
  ]
```

We should also support the same feature in `autoupdate` field though it is used for git auto-update only, once multi-filemap support added, we can migrate `npmName` and `npmFileMap` to `autoupdate` format.

The multi-filemap should looks like this in `package.json` once it's implemented:

``` js
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/cdnjs/cdnjs.git",
    "fileMap": [
      {
        "basePath": "",
        "files": [
          "*.json"
        ]
      },
      {
         "basePath": "",
         "files": [
           "*.js"
        ]
      }
    ]
  }
```

PS: the corresponding issue in main repo is cdnjs/cdnjs#9155

The test cases for `package.json` and example should also be updated at the same time.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Should we still support the old `files` format?

**Comment by PeterDaveHello** [comment]
@IonicaBizau I think yes, or do you have other ideas? I'll prefer to keep that, until the npm + auto-update(r) integration / migration finished.

**Comment by IonicaBizau** [comment]
Sure!

**Comment by IonicaBizau** [comment]
> The test cases for `package.json` and example should also be updated at the same time.

@PeterDaveHello Actually what are the test cases that should be updated? I opened a PR: #24.
