### ISSUE TITLE
Handler on the versions didn't fit the current filemap

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#15]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=26439733)](https://www.bountysource.com/issues/26439733-handler-on-the-versions-didn-t-fit-the-current-filemap?utm_source=26439733&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Currently, I make a fake directory to prevent the updater keep want to add that version, see:
- https://github.com/cdnjs/autoupdate/commit/91e63277994ee660c4a9e256a9665d9ccee359fa
- https://github.com/cdnjs/cdnjs/commit/238871b8accc4c95b178dfa7605995ac3087a047

A better method should be put them in a list, and ignore the lib/ver from the list, and also we can manually checkout the list to see how can we add the versions can not be added by updater, maybe just the filemap changed, sometimes we may need to use an old filemap to add the old versions!

**Comment by denim2x** [comment]
Would it be suitable to have a '.cdnrc' file for addressing this issue?

**Comment by PeterDaveHello** [comment]
I think it could be in the config, or something like ignorelist.
