### ISSUE TITLE
git auto-update: drop the repo cloning mechanism

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#17]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27481988)](https://www.bountysource.com/issues/27481988-git-auto-update-drop-the-repo-cloning-mechanism?utm_source=27481988&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Currently, we clone every repo and check the tags(versions), it just uses too much resource and not efficient. Should add a local cache/repo mechanism to prevent that, and maybe should also add a new method call GitHub rather than git, to use GitHub api for the tags/versions, and just download the tarball of the needed versions.

**Comment by IonicaBizau** [comment]
I would recommend that––it will probably be much slower, and I don't want it to be limited to GitHub only.

**Comment by PeterDaveHello** [comment]
@IonicaBizau yes, I mean improve the one for git repos as general purpose, and one more updater for GitHub only which could be much more efficient, no conflicts here :smile:

**Comment by PeterDaveHello** [comment]
@IonicaBizau by the way if you try to clone all the git auto-update enabled repos (about 1200 repos) , you'll see it's how slow ... use GitHub api for the libs hosted on GitHub will be faster.

**Comment by PeterDaveHello** [comment]
For GitHub auto-updater, I created another issue and bounty at #27
