### ISSUE TITLE
Write unit test

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#18]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27482101)](https://www.bountysource.com/issues/27482101-write-unit-test?utm_source=27482101&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by dakshshah96** [comment]
@PeterDaveHello What type of unit tests are we looking for here? This seems like a really old issue.

**Comment by PeterDaveHello** [comment]
I'm not sure have you written this kind of tests yet, as we call it "unit" test, actually it should test every single behavior in our program, to make sure the future changes won't break the origin functions by accident.

For examples, we should have a example library with corresponding repository, with different tags, including some valid and invalids one, then make sure we can fetch those valid versions, etc.

**Comment by dakshshah96** [comment]
@PeterDaveHello I'm aware of unit tests. Was just learning Chai and Mocha for testing so I asked what specific tests are we looking for 😄

**Comment by PeterDaveHello** [comment]
@dakshshah96 so is that explained? Or you are looking for something else?

**Comment by dakshshah96** [comment]
@PeterDaveHello Explained 👍  By the way, where are the current CI tests located?

**Comment by PeterDaveHello** [comment]
@dakshshah96 Not setup yet, would use Travis CI I think.

**Comment by Charliekenney23** [comment]
Is this still *actually* open? I'd love to write them

**Comment by PeterDaveHello** [comment]
@Charliekenney23 it's still open, yes 😄 If you'd like to know more about how it works, feel free to send some library pull request in [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs) in the meantime :)
