### ISSUE TITLE
Ignore unnecessary files globally

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#25]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=38982175)](https://www.bountysource.com/issues/38982175-ignore-unnecessary-files-globally?utm_source=38982175&utm_medium=shield&utm_campaign=ISSUE_BADGE)

To prevent the file types like `scss`, `ts` been grabbed into the repo.
Whitelist may be easier in this case.

**Comment by denim2x** [comment]
Area you considering having a '.cdnignore' file for this purpose?

**Comment by PeterDaveHello** [comment]
I think it could be in the config, or something like ignorelist, won't prefer a leading point in name prefix.

**Comment by Haroenv** [comment]
Probably useful to encourage the `files` property in the `package.json`

**Comment by PeterDaveHello** [comment]
I'll prefer an individual config file, but anyway, we could have it first and then tune it.
