### ISSUE TITLE
Run a build command after cloning repository

### ISSUE THREAD

**Issue by pioug** [cdnjs/autoupdate#32]
I noticed that angular.js@1.6.7 is not yet available on cdnjs. If I understand correctly, it is not using autoupdater (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angular.js/package.json) for now. 

Unfortunately, the dist files are not directly available in the repo (https://github.com/angular/angular.js) and AFAIK autoupdate does only _git clone_ and _fs copy_ the files. 

Do you think there is room to run a configurable build command in between  🙏 We could use https://www.npmjs.com/package/npm-run for example to run `grunt package` in the case of angular.js.

I can work on a PR it makes sense 👍

**Comment by PeterDaveHello** [comment]
Thanks for suggestion, but I'm sorry, as that's not something I want to support right now, I don't want to build the files from my side, as that's not our goal and will make the process very complex than before, we can't make sure the process is done well in each round, thank you again.
