### ISSUE TITLE
Integrate npm auto-update

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#6]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=24609170)](https://www.bountysource.com/issues/24609170-integrate-npm-auto-update?utm_source=24609170&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Integrate npm auto-update in, and drop the old one in cdnjs/cdnjs:
https://github.com/cdnjs/cdnjs/blob/master/auto-update.js

So the old config:
```js
  "npmName": "jquery",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    }
  ],
```

should be : 
```js
  "autoupdate": {
    "source": "npm",
    "target": "jquery",
    "fileMap": [
      {
        "basePath": "dist",
        "files": [
          "**/*"
        ]
      }
    ]
  }
```

Note that the `package.json`s, corresponding document and test should also be updated.

**Comment by IonicaBizau** [comment]
@PeterDaveHello What is the progress of this issue?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Since this was finally fixed, can I get the [bounty from BountySource](https://www.bountysource.com/issues/24609170-integrate-npm-auto-update)? I am not sure if it will be awarded automatically or not...

**Comment by MattIPv4** [comment]
@IonicaBizau I believe if you submit a claim for it, any backer can approve your claim. It looks like the backers are Peter and the generic cdnjs account here, not sure who has access to that. I'll try to find out for you if Peter can't approve it.

**Comment by IonicaBizau** [comment]
@MattIPv4 Thanks. I've just done that. One backer seem to be the @cdnjs organization itself and the other one is @PeterDaveHello.
