### ISSUE TITLE
Local cache/repo reuse for git auto-update

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/autoupdate#9]
It takes long time to clone the whole repo again and again, also waste too much network bandwidth.
Should support local cache mechanism. Or, do `fetch` in the already cloned repo instead of `clone` a new one.

**Comment by PeterDaveHello** [comment]
Manual local cache reference:
https://github.com/cdnjs/autoupdate/blob/master/local_git_repo_mirror_notes

**Comment by LeaYeh** [comment]
hey @PeterDaveHello , your link is not find.

**Comment by PeterDaveHello** [comment]
Updated.
